### PR TITLE
An initial draft of Workflow-Policies.md

### LINKED ISSUE #2: Create initial version of Github Guidelines
We need a file which dictates how we'll be using github. Some things to cover:
- avoid commits to `master`
- use branches and PR everything in to `master`
- making good/appropriate commits (and commit messages)

This will be the continuation of @beperron's "Github Conventions and Practices" post on Slack.

### PR DESCRIPTION
**Pull request by ClaytonJY**
I think this is a lot less complete/comprehensive than the R Styleguide, so please tell me what you think is missing.

Some things I haven't addressed (should I?):
- Releases/Zenodo/DOI: not sure how often this will come up
- specific git commands: seemed out-of-place, and I imagine many people won't be using git from the command line
- non-standard workflows: if there's any fairly common deviations from the workflow I outlined, they should probably be mentioned in here
- features of GH Issues/PR's: Labels/Milestone/Assignee, auto-closing of issues ("Closes #x").
- what it means to rewrite history: perhaps the most needed thing in this list; I could add a `Rewriting History` section?

I'm also not sold on the file name, as I think this covers a bit more than just Github conventions. What's a more accurate name?

Please view the rich diff to see how the markdown rendersr.

Closes #2.

### CODE REVIEW

**Comment by beperron** [comment]
I'm in agreement with the style guide.  We can add more as we develop, but this is the basis of a strong start.  DOI will be largely irrelevant for the overall project -- only for a specific paper.  

I will need some additional details on `Rewriting History` -- not sure what that means, although I can make a general inference.

Maybe the title should be something like `Workflow Policy` -- we will be documenting how pull requests and code reviews are conducted.  That is part of GitHub, but GitHub is really only a tool to facilitate this process.  I'm open to thoughts, but I think we are ready for a merge.

**Comment by ClaytonJY** [comment]
Okay cool, I like that title and agree there should be a `Rewriting History` section. I won't have a chance to make those before this afternoon's meeting, so I'll roll these suggestions and ones arising from that meeting all together.

**Comment by ClaytonJY** [comment]
Something else to add: tips for making good commits and commit messages

**Comment by beperron** [comment]
This is great.  I am open to revisions suggested by others, but for Clayton's immediate purposes in moving this forward I think this is complete.  I will leave this PR open until others have approved.  Thx.

**Comment by ClaytonJY** [comment]
@hereismyname & @bryanvictor: what do you guys think, anything you'd like me to change or add here right now?

**Comment by bryanvictor** [comment]
Looks great, no additions needed.  I think a "troubleshooting merge errors" section will be very helpful for future versions, but this is ready.

**Comment by hereismyname** [comment]
Looks good thus far-- one thing maybe I was looking for today, was a little more summary on closing of branches. We talked about this more on Slack, but maybe seeing it formalized here would be good. I notice Github tags the closes #X-- does it treat this as a command when I comment online?

**Comment by ClaytonJY** [comment]
@hereismyname want to take a look, and merge this if you're satisfied?

**Comment by hereismyname** [comment]
Looks good. Reading the commit message guidelines you linked to now. I'm merging this.

**Pull request merged**
